version: '2'

volumes:
  orderer.pharma-network.com:
  peer0.manufacturer.pharma-network.com:
  peer1.manufacturer.pharma-network.com:
  peer0.distributor.pharma-network.com:
  peer1.distributor.pharma-network.com:
  peer0.retailer.pharma-network.com:
  peer1.retailer.pharma-network.com:
  peer0.consumer.pharma-network.com:
  peer1.consumer.pharma-network.com:
  peer0.transporter.pharma-network.com:
  peer1.transporter.pharma-network.com:


networks:
  pharma:

services:

  ca.manufacturer.pharma-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturer.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturer.pharma-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/411af9eaf79c70f6508167c440c479a278dccc8891bd88a127d05ba5276ab60d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.manufacturer.pharma-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/411af9eaf79c70f6508167c440c479a278dccc8891bd88a127d05ba5276ab60d_sk
    volumes:
      - ./crypto-config/peerOrganizations/manufacturer.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.manufacturer.pharma-network.com
    networks:
      - pharma

  ca.distributor.pharma-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.distributor.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.distributor.pharma-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a20e15cf1c89f6ff86eb6e2ef92fda82ddc1aa49f6a06a4051f4f13ef0fd2a96_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.distributor.pharma-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a20e15cf1c89f6ff86eb6e2ef92fda82ddc1aa49f6a06a4051f4f13ef0fd2a96_sk
    volumes:
      - ./crypto-config/peerOrganizations/distributor.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.distributor.pharma-network.com
    networks:
      - pharma

  ca.retailer.pharma-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.retailer.pharma-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5f74c4c19bdb5d34a6f39573da55f166327679f75bd170f908d4a452da9b7f84_sk
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.retailer.pharma-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5f74c4c19bdb5d34a6f39573da55f166327679f75bd170f908d4a452da9b7f84_sk
    volumes:
      - ./crypto-config/peerOrganizations/retailer.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.retailer.pharma-network.com
    networks:
      - pharma

  ca.consumer.pharma-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.consumer.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.consumer.pharma-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/aa3e71bad77decca38ed8f1dfa4a9b9462cee142d7fd40f0aa26527131521293_sk
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.consumer.pharma-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/aa3e71bad77decca38ed8f1dfa4a9b9462cee142d7fd40f0aa26527131521293_sk
    volumes:
      - ./crypto-config/peerOrganizations/consumer.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.consumer.pharma-network.com
    networks:
      - pharma        

  ca.transporter.pharma-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.transporter.pharma-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transporter.pharma-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/222cb3526ac909f0982ff1bfa5fc711ee53e71a56e68be947f9edaf83708fa04_sk
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.transporter.pharma-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/222cb3526ac909f0982ff1bfa5fc711ee53e71a56e68be947f9edaf83708fa04_sk
    volumes:
      - ./crypto-config/peerOrganizations/transporter.pharma-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.transporter.pharma-network.com
    networks:
      - pharma

  api.pharma-network.com:
    image: "vineethmaller/hyperledger-fabric-apiserver:latest"
    ports:
      - "8080:8080"
    command: bash -c 'sleep infinity'  
    volumes:
      - ../application/:/home/node/app
      - ./crypto-config/:/home/node/crypto-config
    container_name: api.pharma-network.com
    networks:
      - pharma


  orderer.pharma-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.pharma-network.com
    container_name: orderer.pharma-network.com
    networks:
      - pharma

  peer0.manufacturer.pharma-network.com:
    container_name: peer0.manufacturer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.manufacturer.pharma-network.com
    networks:
      - pharma

  peer1.manufacturer.pharma-network.com:
    container_name: peer1.manufacturer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.manufacturer.pharma-network.com
    networks:
      - pharma

  peer0.distributor.pharma-network.com:
    container_name: peer0.distributor.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.distributor.pharma-network.com
    networks:
      - pharma

  peer1.distributor.pharma-network.com:
    container_name: peer1.distributor.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.distributor.pharma-network.com
    networks:
      - pharma    

  peer0.retailer.pharma-network.com:
    container_name: peer0.retailer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.retailer.pharma-network.com
    networks:
      - pharma

  peer1.retailer.pharma-network.com:
    container_name: peer1.retailer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.retailer.pharma-network.com
    networks:
      - pharma

  peer0.consumer.pharma-network.com:
    container_name: peer0.consumer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.consumer.pharma-network.com
    networks:
      - pharma

  peer1.consumer.pharma-network.com:
    container_name: peer1.consumer.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.consumer.pharma-network.com
    networks:
      - pharma    

  peer0.transporter.pharma-network.com:
    container_name: peer0.transporter.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.transporter.pharma-network.com
    networks:
      - pharma

  peer1.transporter.pharma-network.com:
    container_name: peer1.transporter.pharma-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.transporter.pharma-network.com
    networks:
      - pharma

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-network.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/peers/peer0.manufacturer.pharma-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.manufacturer.pharma-network.com
      - ca.distributor.pharma-network.com
      - ca.retailer.pharma-network.com
      - ca.consumer.pharma-network.com
      - ca.transporter.pharma-network.com
      - orderer.pharma-network.com
      - peer0.manufacturer.pharma-network.com
      - peer1.manufacturer.pharma-network.com
      - peer0.distributor.pharma-network.com
      - peer1.distributor.pharma-network.com
      - peer0.retailer.pharma-network.com
      - peer1.retailer.pharma-network.com
      - peer0.consumer.pharma-network.com
      - peer1.consumer.pharma-network.com
      - peer0.transporter.pharma-network.com
      - peer1.transporter.pharma-network.com
    networks:
      - pharma

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.manufacturer.pharma-network.com:7051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/manufacturer.pharma-network.com/users/Admin@manufacturer.pharma-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - pharma

